server:
  port: 9090
spring:
  application:
    name: pet-clinic
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"
  file:
    path: /app/logs
    name: /app/logs/${spring.application.name}.log
  level:
    root: info
    web: trace
    dev.hobie.sample: debug
